// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnGrNsD1-SfsJmL-zW2LqnYWYAbYLFeUA',
    appId: '1:725974255498:web:6af1a5152556ea38f72a73',
    messagingSenderId: '725974255498',
    projectId: 'leaning-management-syste-163fb',
    authDomain: 'leaning-management-syste-163fb.firebaseapp.com',
    storageBucket: 'leaning-management-syste-163fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTKYq6FMf_waIlD7OiYIPlxkRQ5afkdk',
    appId: '1:725974255498:android:d495475890ebdcc0f72a73',
    messagingSenderId: '725974255498',
    projectId: 'leaning-management-syste-163fb',
    storageBucket: 'leaning-management-syste-163fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJRjQDAJQPgdzGxCpprHXNqIR3PTbJJ_0',
    appId: '1:725974255498:ios:ab4edae81d96b201f72a73',
    messagingSenderId: '725974255498',
    projectId: 'leaning-management-syste-163fb',
    storageBucket: 'leaning-management-syste-163fb.appspot.com',
    iosBundleId: 'com.example.learningManagmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJRjQDAJQPgdzGxCpprHXNqIR3PTbJJ_0',
    appId: '1:725974255498:ios:ab4edae81d96b201f72a73',
    messagingSenderId: '725974255498',
    projectId: 'leaning-management-syste-163fb',
    storageBucket: 'leaning-management-syste-163fb.appspot.com',
    iosBundleId: 'com.example.learningManagmentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnGrNsD1-SfsJmL-zW2LqnYWYAbYLFeUA',
    appId: '1:725974255498:web:97a8749d2df68cc4f72a73',
    messagingSenderId: '725974255498',
    projectId: 'leaning-management-syste-163fb',
    authDomain: 'leaning-management-syste-163fb.firebaseapp.com',
    storageBucket: 'leaning-management-syste-163fb.appspot.com',
  );

}